# Generated by Django 3.2.6 on 2021-08-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Ürün No')),
                ('miad', models.DateField(blank=True, verbose_name='Miad')),
                ('purchase', models.DateField(blank=True, verbose_name='Satış Tarihi')),
                ('stock', models.BooleanField(verbose_name='Stok Durumu')),
            ],
        ),
    ]
