# Generated by Django 3.2.6 on 2021-08-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(null=True, verbose_name='Satış Tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.BooleanField(default=True, verbose_name='Stok Durumu'),
        ),
    ]
