# Generated by Django 3.2.6 on 2021-08-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210827_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=200, verbose_name='Stok Durumu'),
        ),
    ]
