# Generated by Django 3.2.6 on 2021-08-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Satış Tarihi'),
        ),
    ]
