# Generated by Django 3.2.6 on 2021-08-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userregister'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LoginUser',
        ),
    ]
